apiVersion: v1
kind: ConfigMap
metadata:
  
  name: chrony-config
  

data:
  chrony.conf: |+
    # Welcome to the chrony configuration file. See chrony.conf(5) for more
    # information about usuable directives.
    #pool 2.debian.pool.ntp.org iburst

    # This directive specify the location of the file containing ID/key pairs for
    # NTP authentication.
    #keyfile /etc/chrony/chrony.keys
    server ntp.ovh.net  iburst
    # This directive specify the file into which chronyd will store the rate
    # information.
    #driftfile /var/lib/chrony/chrony.drift

    # Uncomment the following line to turn logging on.
    #log tracking measurements statistics
    # Log files location.
    #logdir /var/log/chrony
    allow

    # Stop bad estimates upsetting machine clock.
    maxupdateskew 100.0

    # This directive enables kernel synchronisation (every 11 minutes) of the
    # real-time clock. Note that it can ^`^yt be used along with the 'rtcfile' directive.
    rtcsync

    # Step the system clock instead of slewing it if the adjustment is larger than
    # one second, but only in the first three clock updates.
    makestep 1 3
