apiVersion: v1
kind: Service
metadata:
  name: chrony-service
spec:
  type: NodePort
  selector:
    app: chrony
  ports:
    - protocol: UDP
      port: 123
      targetPort: 123
      nodePort: 30000
